PWD = $(shell pwd)

deploy-stable-vs:
	kubectl apply -f ../hw4/k8s/vs.yaml

deploy-mtls:
	kubectl apply -f ./k8s/pa.yaml

deploy-ra:
	kubectl apply -f ./k8s/ra.yaml

deploy-ap:
	kubectl apply -f ./k8s/ap.yaml